from time import sleep

target = input("Enter Target: ")
port = input("Enter Port: ")
time = input("Enter Time")

print("Loaded 10%")
sleep(5)
print("Loaded 20%")
sleep(5)
print("Loaded 30%")
sleep(5)
print("Loaded 40%")
sleep(5)
print("Loaded 50%")
sleep(5)
print("Loaded 60%")
sleep(5)
print("Loaded 70%")
sleep(5)
print("Loaded 80%")
sleep(5)
print("Loaded 90%")
sleep(5)
print("Loaded 100%")
sleep(5)
print("Sending Attack")
print("Contacting Big Spooky Botnet")
print("Getting confirmation from Brian Krebs")
print("Attack Failed! Reason: Stop ddosing lol")
